apiVersion: v1
kind: Pod
metadata:
  name: vault-client
  namespace: kube-system
spec:
  nodeName: worker-node-1
  containers:
  - image: nginx:latest
    name: nginx
  serviceAccountName: vault-auth
