apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"vault","app.kubernetes.io/name":"vault"},"name":"vault","namespace":"default"},"spec":{"ports":[{"name":"http","nodePort":32001,"port":8200,"targetPort":8200},{"name":"https-internal","port":8201,"targetPort":8201}],"publishNotReadyAddresses":true,"selector":{"app.kubernetes.io/instance":"vault","app.kubernetes.io/name":"vault","component":"server"},"type":"NodePort"}}
  creationTimestamp: "2022-04-08T05:41:58Z"
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
  name: vault
  namespace: default
  resourceVersion: "155734"
  uid: 07bab9fc-01fc-47ee-ac45-6d4997d591c3
spec:
  clusterIP: 10.105.186.164
  clusterIPs:
  - 10.105.186.164
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 32001
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: https-internal
    nodePort: 30353
    port: 8201
    protocol: TCP
    targetPort: 8201
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
